    language: java
jdk:
  - openjdk6
branches:
  only:
    - master
script: mvn -f com.codeaffine.xiliary.releng/pom.xml clean verify
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
after_success: 
  - chmod a+x .travis-deploy.sh
  - ./.travis-deploy.sh